EC_RenameParameters_test <- function (param, value) {
  switch(param,
         "prevalence" == "weighted response weights",
         "var_import" == "resampling",
         "nbcv" == "NbCV",
         "n_trees" == "trees added each cycle",
         "control_xval" == "cross-validations",
         "control_minbucket" == "minimum bucket",
         "control_minsplit" == "minimum split",
         "control_cp" == "complexity parameter",
         "control_maxdepth" == "maximum depth",
         "irls_reg" == "irls.reg",
         "maxit" == "maximum iterations",
         "mgcv_tol" == "convergence tolerance",
         "mgcv_half" == "number of halvings",
         "n_minobsinnode" == "Min observations in terminal node",
         "control_epsilon" == "control: epsilon",
         "control_maxit" == "control: maxit",
         "control_trace" == "control: trace",
         "model" == "Model returned",
         "x" == "x returned",
         "y" == "y returned",
         "qr" == "QR returned",
         "singular_ok" == "Singular fit ok",
         "thresh" == "threshold",
         "maximumiterations" == "Maximum iterations",
         "ntree" == "number of trees",
         "mtry" == "number of variables at each split (mtry)",
         "nodesize" == "node size",
         "maxnodes" == "maximum nodes",
         "pa_ratio" == "absence-presence ratio",
         )
}
